world-name: towny
world-nether: towny_nether
world-end: towny_end
starting-tokens: 16
ubi-tokens: 4
day-count: 0
depend

# Store item worths for End of Day towny box -- Future plans to dynamically update it
# item:X where X is the number of items worth 1 towny token -- Future plans to have a Y parameter for multiple tokens
worth:
  - DIAMOND:8
  - EMERALD:6
  - REDSTONE:28
  - LAPIS_LAZULI:16
  - PORKCHOP:20
  - BEEF:30
  - CHICKEN:64
  - LEATHER:16
  - IRON_BLOCK:6
  - GOLD_BLOCK:8
  - SLIME_BALL:16
  - ENDER_PEARL:24
  - CARROT:64