name: OinkTowny
author: Dendrobyte, Mobkinz78
version: 1.79b
main: com.redstoneoinkcraft.oinktowny.Main
description: OinkTowny plugin made for Oinkcraft's new towny reboot!
softdepend: [Multiverse-Core]
api-version: 1.14
commands:
  oinktowny:
    description: Base oinktowny command
    usage: /<command>
    aliases: [ot]
  superpick:
    description: Super pickaxe for OinkTowny that can't bypass regions
    usage: /<command
    aliases: [super]
permissions:
  oinktowny.admin:
    description: General admin perms. Currently only used for reload.
  oinktowny.bundle:
    description: The basic permission to use the OinkTowny bundle commands
  oinktowny.bundle.name:
    description: Permission to use the bundle of <name>, based on 4th line
  oinktowny.superpick:
    description: The permission to access super pickaxe
  oinktowny.lootdrop:
    description: Allows a player to trigger a lootdrop either at their location or a random one
  oinktowny.claims.admin:
    description: Allows to claim admin claims and bypass claims
  oinktowny.claims.x:
    description: Sets limit for how many claims a player has
  oinktowny.create:
    description: Allows a player to create an arena
  oinktowny.arenas:
    description: Allows a player to create an arena join sign
  oinktowny.ruins:
    description: Allows a player to create ruins
  oinktowny.adminenchant:
    description: Allows a player to enchant an item via command without levels